# 데이터 추가wor

INSERT INTO word (word_eng,mean,bookid) VALUES("inform","알리다, 통지하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("advise","충고하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("service","봉사, 공공 업무, 서비스",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("provide","공급하다, 준비하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("relationship","관계",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("behave","(예의 바르게) 행동하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("improve","향상시키다, 향상하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("individual","개인, 개인의, 개인적인",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("require","필요로 하다, 요구하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("develop","개발하다, 발달하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("social","사회의, 사교적인",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("amount","총계, 양, 총계가 ~이 되다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("employ","고용하다, 쓰다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("terrible","무서운, 끔찍한",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("attitude","태도, 입장",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("research","연구, 연구하다, 조사하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("audience","청중, 관객",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("volunteer","자원봉사, 지원자, 자발적으로 ~하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("influence","영향, 영향을 미치는 것[사람], 영향을 끼치다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("international","국제의, 국제적인",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("opportunity","기회",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("ability","능력",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("expense","비용, 지출",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("involve","포함하다, 관련되다, (사건 등에)말려들게 하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("stress","강조, 스트레스, 강조하다, 압력을 주다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("therefore","그러므로, 그 결과",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("average","평균, 평균의, 평균이 ~가 되다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("ride","(탈 것을) 타다, 태움",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("local","지방의, 지역의, 장소의",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("encourage","촉구하다, 격려하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("determine","결심하다, 결정하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("comfort","편안하게하다, 위로하다, 편안, 위로",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("consume","소비하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("object","물체, 목표, 반대하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("impress","~에게 깊은 인상을 주다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("available","이용 가능한, 쓸모 있는",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("contain","함유하다, 포함하다, 억제하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("recognize","인지하다, 인정하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("material","재료, 물질, 물질의",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("positive","긍정적인, 확신하는",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("emotion","감정",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("amaze","놀라게 하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("reduce","줄이다, 낮추다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("discover","발견하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("essence","(사물의) 본질, 정수",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("benefit","이익, 이익이 되다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("affect","~에 영향을 미치다, ~인 체 하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("level","수준, 수평, 수평의, 평탄하게 만들다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("chemistry","화학, 교감",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("immediate","직접의, 즉각적인",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("thus","그러므로, 따라서",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("proper","적절한, 알맞은",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("profession","직업, 직종",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("economic","경제의, 경제학의",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("cell","세포, 작은 방, 독방",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("focus","초점, 집중하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("issue","논란거리, 발행, 발행물, 발행하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("decide","결심하다, 결정하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("demand","요구하다, 수요",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("occur","(사건이)일어나다, 발생하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("complex","복잡한, 복합체",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("define","정의하다, 한계 짓다, 한정하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("proud","자랑스러워하는, 자만하는",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("aware","인지하는, 알고 있는",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("contact","접촉, 접촉하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("performance","공연, 성적, 성과",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("detail","세부, 상술하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("approach","접근하다, 접근",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("participate","참여하다, 참가하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("fashion","유행, 방식, 만들어 내다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("package","꾸러미, 포장, 포장하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("disappear","사라지다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("career","직업, 경력",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("secure","안전한, 안전하게 하다, 확보하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("novel","(장편)소설, 참신한",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("despite","~에도 불구하고",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("background","배경, 배경지식, 이유",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("solution","해결, 해결책, 용액",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("generate","일으키다, 발생시키다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("eventually","결국",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("decrease","감소, 감소하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("recycle","재활용하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("desire","욕망, 욕구, 바라다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("balance","균형, 은행 잔고, 균형을 이루다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("publish","발표하다, 출판하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("congratulate","축하하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("compose","구성하다, 작문하다, 작곡하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("follow","따라가다, (규칙을) 따르다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("negative","부정적인",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("occasion","경우, 특별한 일",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("replace","대체하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("expert","전문가",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("term","기간, 학기, 용어",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("relieve","경감하다, 안도시키다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("describe","묘사하다, 표현하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("biology","생물학",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("due","만기의, ~하기로 되어 있는",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("equipment","장치, 장비",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("account","은행 계좌, 이야기, 설명하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("birth","탄생",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("constant","일정한, 불변의, 상수",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("genius","천재, 천재성",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("reflect","반영하다, 반사하다, 숙고하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("cause","~의 원인이 되다, 원인",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("frequent","빈번한, 종종 방문하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("steady","안정된, 한결같은, 꾸준한",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("extreme","극단의, 극단",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("tend","~하는 경향이 있다(to), 돌보다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("insist","주장하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("extend","연장하다, 넓히다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("politics","정치, 정치학",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("lonely","외로운",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("habitat","서식지, 주거지",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("mental","정신의",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("factor","요인, 요소",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("exchange","교환하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("active","활동적인, 적극적인",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("species","(생물 분류상의) 종",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("athletic","운동의, 운동 경기의",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("dental","치아의",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("delight","기쁨, 기쁘게 하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("confident","자신 있는",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("gradually","점차, 차츰",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("electricity","전기",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("shadow","그림자, 그늘지게 하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("access","접근, 이용, (인터넷을) 이용하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("announce","발표하다, 알리다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("allow","허락하다, 인정하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("firm","확고한, 단단한, 회사",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("vary","바꾸다, 변하다, 다르다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("injure","~에게 상처를 입히다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("permit","허락하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("threat","위협, 협박",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("flood","홍수, 범람시키다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("disabled","무능력의, 장애의",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("lack","부족, ~가 부족하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("signify","의미하다, 중요하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("concentrate","집중하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("emphasize","강조하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("astronomy","천문학",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("commerce","상업, 교역",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("capable","능력 있는, ~을 할 수 있는",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("fuel","연료, 연료를 가하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("manufacture","제조, 제품, 제조하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("movement","움직임, 운동",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("combine","결합시키다, 겸하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("gene","유전자",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("response","응답, 반응",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("victim","희생, 희생자",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("pressure","압력, 압박, 압력을 가하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("accompany","동반하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("frustrate","좌절시키다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("construct","건설하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("dwindle","점점 줄어들다, 저하되다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("increase","(수량이) 늘다, 증가, 이자",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("entertain","즐겁게 하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("predict","예언하다, 예측하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("apologize","사과하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("sight","시야, 광경, 시력",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("quantity","양",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("conclude","결론짓다, 끝내다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("donate","기부하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("personality","개성, 성격, 특색",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("struggle","싸우다, 노력하다, 노력, 투쟁",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("electronic","전자의",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("absorb","흡수하다, (사람·마음을) 열중시키다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("advantage","이익, 유리한 점",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("incredible","(믿기 어려울 만큼) 굉장한, 믿을 수 없는",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("enable","가능하게 하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("instruction","지시, 제품 사용 설명서, 가르침",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("assume","추정하다, (태도 등을) 취하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("attempt","시도하다, 시도",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("variety","다양성, 다양",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("confuse","혼동하다, 혼란시키다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("indicate","지적하다, 나타내다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("analyze","분석하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("labor","노동, 산고, 노동하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("remark","의견, 주목, 의견을 말하다, ~에 주목하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("moral","도덕적인",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("embarrass","당황한",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("claim","요구, 주장, 주장하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("stock","재고품, 저장, 가축, 저장하다, (물품을) 들여놓다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("resident","거주자",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("reasonable","논리적인, 분별력이 있는",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("interrupt","방해하다, 중단하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("discount","할인, 할인하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("creature","생물, 피조물",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("heal","치료하다, 낫게 하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("stranger","낯선 사람, 문외한",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("revolution","혁명, 갑작스런 변화, 회전",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("criticize","비난하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("convince","확신시키다, 납득시키다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("feature","특징, ~를 특징으로 하다, 주연하다, 특집기사, 얼굴 생김새",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("tide","조수(潮水)",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("establish","설립하다, 재정하다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("obtain","획득하다, 통용되다, 행해지다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("assist","도움을 주다",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("disaster","재해, 재앙, 재난",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("efficient","효율적인, 유능한",1);
INSERT INTO word (word_eng,mean,bookid) VALUES("terrific","굉장한, 훌륭한",1);


